language: python
sudo: false
python:
  - 3.6
  - 3.5
env:
  matrix:
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=py35
    - TOXENV=py36
    - TOXENV=pypy
matrix:
  exclude:
    - python: 3.6
      env: TOXENV=py27
    - python: 3.6
      env: TOXENV=py33
    - python: 3.6
      env: TOXENV=py34
    - python: 3.6
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=pypy
    - python: 3.5
      env: TOXENV=py36
  fast_finish: true
addons:
  apt:
    packages:
      - libxmlsec1-dev
      - swig
install:
  - pip install tox -U pip
script:
  - tox -e $TOXENV
